### ISSUE TITLE
Add greek letters to the math editor

### ISSUE THREAD

**Issue by awlnx** [XimeraProject/server#215]
should be very easy, simply add a button to insert the unicode character.

**Comment by kisonecat** [comment]
In https://github.com/XimeraProject/server/commit/ded3b8185947da1a000f496138c791fc5606c562 I added theta, but are there more Greek letters we should add to the top bar?

**Comment by bartsnapp** [comment]
We need phi (varphi) too

**Comment by StevenGubkin** [comment]
rho is probably the third most common.  I do think that all of the Greek
letters should be usable as variables in the parser, and usable with the
input.  Maybe a separate "page" in the math editor for all the Greek
letters would be good?  Similar to UI for texting.

Also, is there a reason we are still using WYSIWYG with preview rather than
using MathQuill?

Peace,
Steve

**Comment by kisonecat** [comment]
I've added phi as @bartsnapp bartsnapp asked, and rho as @StevenGubkin asked.

@StevenGubkin: all the Greek letters are available, and we're not using https://github.com/mathquill/mathquill but we are using https://github.com/daniel3735928559/guppy which you can access by clicking on "Math Editor" at the top of the screen,

**Comment by kisonecat** [comment]
https://github.com/XimeraProject/server/commit/8fda2fae1276d02effb1c42b45e74f8929333117 adds these letters.
