### ISSUE TITLE
/mooculus/continuity/exercises/exerciseList

### ISSUE THREAD

**Issue by rudrarpatel** [XimeraProject/server#434]
I cannot do the homework because in most of the problems it says [Math Processing Error]. Kindly help me.   This is what it says -> 

 Simplify the expression
4x−2+1xx+3−4x−2.
Show your work as indicated below.
First, we multiply the numerator and the denominator by the lowest common denominator

[Math Processing Error] and obtain that [Math Processing Error] Then we simplify the numerator and the denominator. [Math Processing Error]

**Comment by bartsnapp** [comment]
Hi, this typically happens when your browser setting is not correct. 

**First possible solution:**
Clear browser cookies
Close the browser.
Open the browser and log in to Carmen.
Go to the assignment.


**Second possible solution:**
Find one of the pages this is happening, (see attached)
Put your mouse over the "math processing error"
Now, "right-click" and select "accessibility" If collapsible math is checked, uncheck it.
Reload the page.


Check out go.osu.edu/ximerahelp
